### PR TITLE
The bug when lastSlide is not multiple of displaySlideQty is fixed

### PR DESCRIPTION
**Pull request by ghost**
When lastSlide is not multiple of displaySlideQty is fixed and infiniteLoop is false the 'next' buttons is never hidden.

### CODE REVIEW

**Comment by sattes-faction** [comment]
Please accept - it's working :-)

**Comment by selfthinker** [comment]
Just for the record, these issues are all duplicates: #17, #49, #62, #71 (and probably some more).

**Comment by ankitbansal15** [comment]
Please have a look at this bug:
https://github.com/wandoledzep/bxslider/issues/111

**Comment by stevenwanderski** [comment]
Thank you all! Merged and fixed.

**Pull request closed without merging**
